# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

[header]
  layout = "basic" # valid options: basic, fixed

[footer]
# showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/header.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background
  layoutBackgroundBlur = false # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/kame404/kame404.com/tree/main/content/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = false
  showSummary = true
  sharingLinks = ["twitter","facebook","pinterest","email"]

[list]
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background
  showBreadcrumbs = true
  showSummary = false
  #showViews = true
  #showLikes = true
  showTableOfContents = true
  showCards = true
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  apiKey = "AIzaSyATyAj1jhZsM2tE1sQxmpNi64d-xrUlauw"
  authDomain = "kame404-com.firebaseapp.com"
  projectId = "kame404-com"
  storageBucket = "kame404-com.appspot.com"
  messagingSenderId = "328101952183"
  appId = "1:328101952183:web:957401f70a2156f343ab32"
  measurementId = "G-Q3NVPQWYY8"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
